apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: anastasija-c/nginx-kubernetes
      ports:
        - containerPort: 80
